name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: |
            - args: ['--frozen-lockfile']
      - name: Build Plugin
        run: pnpm run -C packages/plugin build
      - name: Before zip
        run: |
          mkdir plugin
          mkdir plugin/latelib
          mv packages/plugin/dist/* plugin/latelib
      - uses: TheDoctor0/zip-release@v0.3.0
        with:
          directory: plugin
          filename: 'latelib-${{ github.ref_name }}.zip'
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'plugin/latelib-${{ github.ref_name }}.zip'
          draft: true
          name: 'LateLib ${{ github.ref_name }}'
